### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by jbixon13** [CodeForBaltimore/COVID-19-response#2]
### Task
Create landing page and branching paths for different use-cases

### Acceptance Criteria
- [ ] Simple interface for selecting what you need info on
- [ ] Components for each path created and routed

**Comment by c-malecki** [comment]
Since we decided we want to make a centralized landing page, do we still want to keep a navbar at the top of the page as well? Or should I integrate the navbar into the landing page as more of a dashboard style navigation? Or split them so that there is a header essentially with the CfB logo and search form and then links within the dashboard portion?
